Cargo.toml
src/error.rs
src/lib.rs
src/rpc.rs

* Remove dependency on tokio, submit returns a future
* Enable logging in tests
* Add fetch, fetch_or, fetch_or_default

Misc changes

---

src/lib.rs

Signed-off-by: daogangtang <daogangtang@gmail.com>

adding srml_system::CheckVersion to SignedExtra in tests in lib.rs.

---

Cargo.toml
src/lib.rs
src/rpc.rs

Rel: https://github.com/paritytech/substrate/pull/3430, https://github.com/polkadot-js/api/pull/1324
Depends on https://github.com/paritytech/substrate/pull/3471

Fetch runtime version and add to extrinsic payload

---

src/extrinsic.rs

rel: https://github.com/paritytech/substrate/pull/4148

Implement DispatchInfo type for SignedExtension

---

Cargo.toml
LICENSE_TEMPLATE
src/error.rs
src/events.rs
src/extrinsic.rs
src/frame/balances.rs
src/frame/contracts.rs
src/frame/mod.rs
src/frame/system.rs
src/lib.rs
src/metadata.rs
src/rpc.rs
src/runtimes.rs

- Use thiserror instead of derive_more
- Format code
- Fix clippy warnings
- Add LICENSE_TEMPLATE
Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Use thiserror instead of derive_more

---

Cargo.toml
src/rpc.rs

rel https://github.com/paritytech/substrate/pull/4184/files

Update to latest substrate changes

---

Cargo.toml
src/error.rs
src/extrinsic.rs
src/frame/balances.rs
src/frame/system.rs
src/lib.rs
src/metadata.rs
src/rpc.rs
src/runtimes.rs

rel https://github.com/paritytech/substrate/pull/4223

New substrate crate renames

---

src/events.rs

`PhantomData` types and aliases are usually of size 0 so are skipped over in deserialization. This PR protects against different fully qualified namespaces.

Ignore PhantomData primitives type sizes

---

Cargo.toml
src/events.rs
src/frame/balances.rs
src/frame/contracts.rs
src/frame/system.rs
src/lib.rs
src/rpc.rs
src/runtimes.rs

Latest substrate updates

---

CHANGELOG.md
Cargo.toml
README.md
src/metadata.rs

Preparing for release to crates.io

Release v0.5.0

---

examples/kusama_balance_transfer.rs
examples/submit_and_watch.rs
src/extrinsic.rs
src/frame/system.rs
src/lib.rs

Some runtimes don't want to use the DefaultExtra. Used by the sunshine dao. cc @4meta5

Custom extra

---

Cargo.toml
proc-macro/Cargo.toml

- Add version and metadata to proc-macro crate
- Bump codec version

v0.7.0 release extras

---

examples/transfer_subscribe.rs

adds example to subscribe to transfer events

event subscription example

---

Cargo.toml

From https://crates.io/crates/wabt

Fix build error, wabt 0.9.2 is yanked

---

src/events.rs

register type sizes for u64 and u128

---

src/lib.rs

Discovered here: https://github.com/paritytech/substrate-subxt/pull/227#discussion_r581038469

Fix type sizes check

---

client/src/lib.rs

re-export WasmExecutionMethod for downstream usage

---

Cargo.toml
client/Cargo.toml
client/src/lib.rs
src/error.rs
src/lib.rs

Required to enable timeouts, see: https://github.com/paritytech/jsonrpsee/issues/284

deps: update jsonrpsee 0.3.0

---

src/rpc.rs

impl From<Arc<WsClient>> and From<Arc<HttpClient>>

---

cli/Cargo.toml
codegen/Cargo.toml

Add missing cargo metadata fields for new crates

---

tests/integration/frame/timestamp.rs

Small test for querying the timestamp pallet

Add timestamp pallet test

---

src/error.rs

This should fix the CI failure spotted on master.

Add TooManyConsumers variant to track latest sp-runtime addition

---

README.md

Add [`crunch`](https://github.com/turboflakes/crunch) to the _real world_ section in the readme file

add crunch to readme

---

README.md

add interbtc-clients to real world usage section

---

CHANGELOG.md
Cargo.toml
cli/Cargo.toml
codegen/Cargo.toml
macro/Cargo.toml
test-runtime/Cargo.toml

Release preparation for v0.16.0

Release prep for v0.16.0

---

subxt/src/lib.rs

export RuntimeError struct

---

subxt/src/error.rs
subxt/src/lib.rs

remove unused PalletError struct

---

subxt/Cargo.toml

bump jsonrpsee to v0.9.0

---

subxt/Cargo.toml

bump jsonrpsee to v0.10.1

---

CHANGELOG.md
RELEASING.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
integration-tests/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
test-runtime/Cargo.toml

Release v0.21.0

---

.github/dependabot.yml

Dependabot :robot: 

---

CHANGELOG.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
subxt/src/lib.rs
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml
testing/ui-tests/Cargo.toml

Have a good look over the changelog; I wrote up a description on how to accomodate the main breaking changes; did I miss anything that's worth adding here?

Release prep for 0.23

---

README.md

Add Staking Miner and Introspector to usage list

---

testing/integration-tests/src/frame/contracts.rs
testing/integration-tests/src/frame/sudo.rs

Fixes https://github.com/paritytech/subxt/actions/runs/3058770071

Fix latest substrate compatibility check

---

testing/integration-tests/src/frame/contracts.rs

Fix contracts integration test

---

cli/Cargo.toml
codegen/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
scripts/publish.sh
subxt/Cargo.toml
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml
testing/ui-tests/Cargo.toml
testing/wasm-tests/Cargo.toml

Add and adapt a publish.sh utility script from jsonrpsee

---

subxt/src/error.rs

Just a small PR with changes very need for my tiny tool.

Make verbose rpc error display

---

examples/examples/dynamic_multisig.rs
examples/examples/multisig.rs
testing/integration-tests/src/frame/balances.rs

This should make the CI green again, as the lints have been introduced in a new stable release, outside of the changes made in this repository.

ci: Appease Clippy

---

CHANGELOG.md
Cargo.lock
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml
testing/ui-tests/Cargo.toml

Bump versions and add changelog entry for 0.26 release.

Prep for releasing 0.26.0

---

Cargo.toml
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
testing/integration-tests/Cargo.toml

chore: use workspace inheritance for package info

---

README.md

Add ink! as a user of `subxt`

---

testing/integration-tests/src/utils/node_proc.rs

Apply clippy fix to unblock the CI clippy step.

testing: Fix clippy

---

testing/integration-tests/src/client/mod.rs
testing/integration-tests/src/frame/balances.rs

Fixes https://github.com/paritytech/subxt/issues/870

Fix integration test for balances
