paritytech/subxt

Cargo.toml
README.md
src/error.rs
src/lib.rs
src/metadata.rs
src/rpc.rs

Depends on paritytech/substrate#3329

Make generic

---

src/lib.rs
src/metadata.rs
src/rpc.rs

- Changes `T::AccountId` to `<T::Lookup as StaticLookup>::Source`
- Adds `Encoded` to avoid encoding a call twice
- `create_and_submit_extrinsic` returns immediately
- fix payload format to match master

Get it to work.

---

Cargo.toml
src/rpc.rs

Was moved from chain::number::NumberOrHex to substrate_rpc_primitives::number::NumberOrHex changed recently in https://github.com/paritytech/substrate/pull/3563

add `substrate-rpc-primitives` to use `NumberOrHex` in rpc.rs

---

Cargo.toml
src/error.rs
src/events.rs
src/lib.rs
src/metadata.rs
src/rpc.rs
src/srml/contracts.rs
src/srml/system.rs

Removes the requirement for a top level `Event` enum to match the substrate runtime. Instead all the events for a given named module can be retrieved and decoded directly to the module `Event` enum.
This decouples the use of events from a specific substrate chain/runtime definition.

Opaque events

---

Cargo.toml
src/error.rs
src/extrinsic.rs
src/lib.rs
src/srml/balances.rs
src/srml/contracts.rs
src/srml/system.rs

This PR removes the requirement of a concrete implementation of a substrate runtime (e.g. `node_runtime`).
The main change here is to copy the "Check" types across from substrate which add additional signed data to an extrinsic. This allows us to break the dependency on `srml_system::Trait` for which a concrete implementation is required. Instead we can use the local `System` trait which defines only the types we need. 
Additionally if the user does still want to use their predefined substrate Runtime - this PR provides some blanket impls for converting to the local traits.

Remove runtime dependency

---

Cargo.toml
src/extrinsic.rs
src/lib.rs
src/runtimes.rs

Matches concrete type definitions in substrate's `node_runtime` for convenience.

Define `node_runtime` compatible Runtime types

---

src/srml/balances.rs
src/srml/system.rs

change introduced on master by https://github.com/paritytech/substrate/pull/3821/files
basically Debug is now required in wasm as well but deriving debug in no-std must be made with https://crates.parity.io/substrate_debug_derive/index.html to avoid bloating the wasm blob.

Fix for substrate master

---

src/rpc.rs

Instead of panicking when the storage data received cannot be decoded we pass on the error.

Don’t panic on storage decode error

---

src/metadata.rs

Event arguments in the metadata are treated as `Vec` instead of `HashSet`. This fixes an issue with event arguments of the same name.
For example the `Balances::Transfer` event has four arguments: `AccountId` (from), `AccountId` (to), `Balance` (value), `Balance` (fee). Before this change the code would only try to parse the two distinct arguments `AccountId` and `Balance` and decoding would fail.

Event arguments are Vec not HashSet

---

Cargo.toml

In relation to this: https://github.com/paritytech/substrate/pull/4012
allows subxt to  compile against latest substrate master

update deps for jsonrpc

---

Cargo.toml
src/events.rs
src/lib.rs
src/metadata.rs
src/rpc.rs

Same as Events, modules with no calls should be ignored when calculating
the module index.

Fix the module index used to create a encoded func

---

Cargo.toml
src/events.rs
src/frame/balances.rs
src/frame/system.rs
src/lib.rs
src/rpc.rs

These dependencies were just used to construct a set of runtime types from a supplied runtime implementation. However this significantly increased the compilation time. Removing `balances` and `contracts` halved the build time from ~8min to ~4min.
Note that we still use `indices` for the `Address` type, and also dev dependencies still have these big substrate dependencies.

Remove pallet crates to improve compilation time

---

Cargo.toml
src/frame/system.rs

Fixes compilation error against latest substrate

Add FromStr constraint to BlockNumber, bump version

---

src/metadata.rs

Implementation copied from https://github.com/paritytech/substrate/blob/6e0a4877afbe2309e106b84333bb70200531b604/frame/support/src/hash.rs#L78 since the StorageHasher trait is not exposed publicly.

Support Blake2_128Concat key hashing

---

examples/submit_and_watch.rs
src/events.rs
src/frame/contracts.rs
src/lib.rs
src/metadata.rs
src/rpc.rs

Previously if any primitive type for an Event didn't have its type size registered it would fail. This PR relaxes that constraint, but it will still fail if we receive one of those Events with a missing type size registration. To address this, the API no allows registering of type sizes by the user, so the library does not need to be updated to have all primitive types registered. 
New API:
```
xt.watch()
.events_decoder(|decoder| {
decoder.register_type_size::<(u64, u64)>("IdentificationTuple")
})
.submit(balances::transfer::<Runtime>(dest.clone().into(), 10_000))
```
The refactoring here should make it easier to add back static event decoding (#28)

Improve dynamic events type sizes API

---

src/frame/balances.rs
src/frame/system.rs
src/lib.rs
src/rpc.rs
src/runtimes.rs

* Generic `Extrinsic` on `System`.
* `Client::storage` takes `Option<T::Hash>` as a second argument.

Generic Extrinsics, storage at hash

---

src/frame/balances.rs
src/frame/contracts.rs
src/frame/system.rs
src/lib.rs
src/rpc.rs
src/runtimes.rs

Introduced in https://github.com/paritytech/substrate/pull/4895

Use new AccountInfo struct for "System Account" storage data

---

Cargo.toml
src/error.rs
src/lib.rs
src/rpc.rs

Substrate dependencies are now on crates.io, so this PR switches to the released crates. 
Also makes it work with the latest version of jsonrpsee, which is incidentally the only github dependency remaining before we can release to crates.io ourselves.

Upgrade to substrate alpha.3 crates.io dependencies

---

examples/kusama_balance_transfer.rs
src/runtimes.rs

Adds a kusama runtime: it has `type Address = AccountId` and no contracts module.

Add kusama runtime and example

---

src/lib.rs

ref to  #82  - explore the method on `Client`

create raw payload in Client

---

src/lib.rs

SignedPayload does not have `decode` implemented, as it is encoded [depending on the length](https://substrate.dev/rustdocs/master/src/sp_runtime/generic/unchecked_extrinsic.rs.html#198). 
Returning the struct allow for different usage, as well as to be signed.

Raw payload return SignedPayload struct

---

Cargo.toml
proc-macro/Cargo.toml
src/events.rs
src/frame/contracts.rs
src/frame/system.rs

Updates to latest alpha.7 release, and fixes the contracts tests.
Note that we need to remove the temporary `Balances` type size registration once #102 is merged.

Update to substrate alpha.7 release

---

Cargo.toml
proc-macro/src/call.rs
src/frame/balances.rs
src/lib.rs
src/signer.rs

This is needed for hardware wallets, which require human confirmation to
sign transactions.  Blocking on a human to sign transactions is not a
good idea, and the signing might fail for many reasons (device
unplugged, authorization not granted, etc).

Make signing fallable and asynchronous

---

.github/workflows/rust.yml
Cargo.toml
README.md
client/.gitignore
client/Cargo.toml
client/gen-chain-spec.sh
client/purge-chain.sh
client/run.sh
client/src/lib.rs
proc-macro/Cargo.toml
src/frame/balances.rs
src/lib.rs
src/runtimes.rs

This let's the `ClientBuilder` specify a `jsonrpsee::Client` and implements a `jsonrpsee::ClientTransport` that wraps a substrate light client.
TODO:
- [0] https://github.com/paritytech/substrate/pull/6313
Closes #49

Support embedded full/light node clients.

---

Cargo.toml
client/Cargo.toml
client/src/lib.rs
proc-macro/Cargo.toml
proc-macro/src/call.rs
proc-macro/src/event.rs
proc-macro/src/lib.rs
proc-macro/src/module.rs
proc-macro/src/store.rs
proc-macro/src/test.rs
proc-macro/src/utils.rs
src/error.rs
src/events.rs
src/extra.rs
src/frame/balances.rs
src/frame/mod.rs
src/frame/sudo.rs
src/frame/system.rs
src/lib.rs
src/metadata.rs
src/rpc.rs
src/runtimes.rs
src/signer.rs

- Improves error messages in proc-macros (closes #122)
- Makes Signature and Extra associated types of a Runtime trait
- Removes special casing of system events
- If an extrinsic fails `watch` will return an error (closes #103)
- Adds support for decoding runtime error names from metadata
- Adds sudo to test for `BadOrigin` errors (closes #112)
- Adds a test to balances module to test for `InsufficientBalance` error

Improve error handling in proc-macro's.

---

Cargo.toml
client/Cargo.toml
client/gen-chain-spec.sh
client/purge-chain.sh
client/run.sh
client/src/lib.rs
proc-macro/Cargo.toml
src/frame/balances.rs
src/lib.rs
src/rpc.rs
src/subscription.rs
test-node/Cargo.toml
test-node/build.rs
test-node/runtime/Cargo.toml
test-node/runtime/build.rs
test-node/runtime/src/lib.rs
test-node/src/chain_spec.rs
test-node/src/cli.rs
test-node/src/command.rs
test-node/src/lib.rs
test-node/src/main.rs
test-node/src/service.rs

When subscribing to events there are two common use cases:
- Finding events emitted after submitting an extrinsic
- Subscribing to a specific event
This makes it easier to subscribe to a specific event.
@ascjones would it be possible to create a new release after this? Looks like we have all we need for sunshine-identity for now.

Events sub

---

src/lib.rs

Closes #68 
No tests because there are no modules in substrate that take unsigned extrinsics from external sources afaik

Support unsigned extrinsics.

---

CHANGELOG.md
Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml
test-node/runtime/Cargo.toml

* Rc5 [#143](https://github.com/paritytech/substrate-subxt/pull/143)
* Refactor: extract functions and types for creating extrinsics [#138](https://github.com/paritytech/substrate-subxt/pull/138)
* event subscription example [#140](https://github.com/paritytech/substrate-subxt/pull/140)
* Document the `Call` derive macro [#137](https://github.com/paritytech/substrate-subxt/pull/137)
* Document the #[module] macro [#135](https://github.com/paritytech/substrate-subxt/pull/135)
* Support authors api. [#134](https://github.com/paritytech/substrate-subxt/pull/134)

Release v0.11.0

---

examples/fetch_all_accounts.rs
proc-macro/src/store.rs
proc-macro/tests/balances.rs
src/lib.rs
src/rpc.rs

Storage map iter

---

src/metadata.rs

This is needed for Ledgeracio.

Implement the `concat` in `twox_64_concat`

---

src/error.rs
src/events.rs
src/frame/balances.rs
src/frame/sudo.rs
src/subscription.rs

If an extrinsic in a block fails, all extrinsics will report a failure. We check the phase when watching an extrinsic and ignore errors of other extriniscs.

Only return an error if the extrinsic failed.

---

CHANGELOG.md
Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml

* Only return an error if the extrinsic failed. [#156](https://github.com/paritytech/substrate-subxt/pull/156)
* Update to rc6. [#155](https://github.com/paritytech/substrate-subxt/pull/155)
* Different assert. [#153](https://github.com/paritytech/substrate-subxt/pull/153)
* Add a method to fetch an unhashed key, close #100 [#152](https://github.com/paritytech/substrate-subxt/pull/152)
* Fix port number. [#151](https://github.com/paritytech/substrate-subxt/pull/151)
* Implement the `concat` in `twox_64_concat` [#150](https://github.com/paritytech/substrate-subxt/pull/150)
* Storage map iter [#148](https://github.com/paritytech/substrate-subxt/pull/148)

Release v0.12.0

---

src/events.rs
src/metadata.rs

A lot of code shift here is due to `cargo fmt`, I can revert this if needs be. The main change here is to enable `Option` decoding, required for [PolkaBTC](https://github.com/interlay/BTC-Parachain/blob/master/crates/staked-relayers/src/lib.rs#L1039).
EDIT: `cargo +nightly fmt` fixed it, thanks @dvc94ch

decode option event arg

---

src/metadata.rs

I faced that I could not use Metadata's main functions outside of the crate and don't see any reason why these functions should be invisible to outside.

Remove visibility limiter `pub (crate)` from Metadata

---

src/events.rs
src/metadata.rs

The previous fix was not complete, we need to update the output bytes to indicate whether the `Option` is `Some` or `None`. I've also added a small test to validate this against the codec library.

fix option decoding and add basic sanity test

---

Cargo.toml
src/frame/contracts.rs
src/runtimes.rs

- Revert contracts put_code test to pure code (not using the `subxt_test` macro), for better readability and debuggability (is that a word?)
- Add runtime for the node template with the contracts module added. 
- Add `integration-tests` feature for tests which require a running substrate node, instead of just `#[ignore]`ing them

Fix up contracts pallet tests

---

src/events.rs

So that printing the `RawEvent` won't take more space than the whole screen.

Display RawEvent data in hex

---

src/extrinsic/signer.rs

This is needed for Ledgeracio, as Ledgeracio’s signer is now no longer `Send`.

Remove unnecessary Sync requirements

---

.github/workflows/rust.yml
src/extrinsic/signer.rs

Signed-off-by: koushiro <koushiro.cqx@gmail.com>

Derive `Clone` for `PairSigner`

---

src/events.rs

decode DispatchInfo on ExtrinsicFailed events

---

Cargo.toml
src/lib.rs
src/rpc.rs
src/runtimes.rs

Removes some big substrate dependencies which were only being used for one or two types. I have just copied these over verbatim, which is acceptable since we are targeting a specific version of substrate at the moment.
This shaves about a minute off the compile time, down from 3:42 to 2:46 on my machine.

Remove some substrate dependencies to improve compile time

---

src/metadata.rs

Closes #205 
Example of new public api usage and outputs
```Rust
let client = ClientBuilder::<KusamaRuntime>::new().build().await?;
let block_hash_count_meta = client.metadata()
.module("System")?
.constant("BlockHashCount")?;
println!("name: {:#?}\n value: {:#?}\n ty: {:#?}\n documentation: {:#?}\n",
block_hash_count_meta.name(),
block_hash_count_meta.value::<u32>()?,
block_hash_count_meta.ty(),
block_hash_count_meta.documentation()
);
// name: "BlockHashCount"
// value: 2400
// ty: "T::BlockNumber"
// documentation: [
//    " The maximum number of blocks to allow in mortal eras.",
// ]

feat: Enable retrieval of constants from runtime metadata

---

src/extrinsic/mod.rs

`Extra` types are configurable within the runtime and not every single blockchain uses the default parameters. By re-exporting these types, users will only have to reference them instead of duplicating code implementation.

Export extra types

---

Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml
test-node/Cargo.toml

Upgrade dependencies, bumps substrate to 2.0.1

---

src/frame/system.rs

This is introduced since https://github.com/paritytech/substrate/commit/2c87fe171bc341755a43a3b32d67560469f8daac
https://github.com/paritytech/substrate/blob/fa404167bbfe7bfd459689d25fc19b86da698367/frame/system/src/lib.rs#L278-L285

Add event Phase::Initialization

---

Cargo.toml
proc-macro/src/module.rs
proc-macro/src/utils.rs
src/events.rs
src/frame/session.rs
src/frame/staking.rs

Fixes #196, fixes #181, fixes #28
Before this change, the event decoder assume all the event types have fixed sizes. Some counterexamples are: Hashes, AuthorityList.
In this change, instead of decoding by skipping the fixed-length bytes, we introduce `type_segmenter` registry which decodes the raw event bytes with the actual scale codec. So variable length types can be handled correctly.
In the past, trait associated type is the only way to add types to the EventsDecoder implementation of a pallet. But in reality it's common that the events in a pallet references some types not defined in the trait associated types. Some examples are: `IdentificationTuple` and `SessionIndex` in Session pallet.
In this change, we introduce more attributes to add the types:
```rust
#[module]
trait Pallet: …
```

Refactor event type decoding and declaration

---

src/rpc.rs

`query_storage_at()` is supposed to call `state_queryStorageAt(keys, hash)` instead of `state_queryStorage(keys, from, to)`. 
Before this fix, a call to the function is equal to `state_queryStorage(keys, hash, null)`. So the responded `StorageChangeSet` includes everything from the given hash to the latest block. I found this problem because the assertion in the iterator fails:
https://github.com/paritytech/substrate-subxt/blob/4725a33ea25c066bb7773a2e9d301498ea156568/src/lib.rs#L250

Fix the wrong rpc call in query_storage_at()

---

CHANGELOG.md
Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml

* Refactor event type decoding and declaration [#221](https://github.com/paritytech/substrate-subxt/pull/221)
* Add Balances Locks [#197](https://github.com/paritytech/substrate-subxt/pull/197)
* Add event Phase::Initialization [#215](https://github.com/paritytech/substrate-subxt/pull/215)
* Make type explicit [#217](https://github.com/paritytech/substrate-subxt/pull/217)
* Upgrade dependencies, bumps substrate to 2.0.1 [#219](https://github.com/paritytech/substrate-subxt/pull/219)
* Export extra types [#212](https://github.com/paritytech/substrate-subxt/pull/212)
* Enable retrieval of constants from rutnime metadata [#207](https://github.com/paritytech/substrate-subxt/pull/207)
* register type sizes for u64 and u128 [#200](https://github.com/paritytech/substrate-subxt/pull/200)
* Remove …

Release v0.14.0

---

client/Cargo.toml
client/src/lib.rs
src/lib.rs

expose wasm execution method on subxt client config

---

src/rpc.rs

rpc client methods should be public for downstream usage

---

Cargo.toml
client/src/lib.rs
src/lib.rs
src/rpc.rs

implement session handling for unsubscribe in subxt-client

---

src/lib.rs
src/rpc.rs
src/subscription.rs

Closes #238
- Adds RPC method to subscribe to finalized block headers and retrieve storage changes per block.
- Update extrinsic watcher to wait for finalization.
- Also fixes the method name for the following unsubscribe calls...
https://github.com/paritytech/substrate-subxt/blob/9959f0d29950219f20b5cc79dfff46f8987239fc/src/rpc.rs#L465
https://github.com/paritytech/substrate-subxt/blob/9959f0d29950219f20b5cc79dfff46f8987239fc/src/rpc.rs#L481

implement variant of subscription that returns finalized storage changes

---

src/error.rs
src/lib.rs

export module error for downstream usage

---

src/subscription.rs

return none if subscription returns early

---

Cargo.toml

Closes #262 
As `substrate` and some of the Rust ecosystem hasn't updated to `tokio 1` yet, let's make it configurable to support either `tokio0.2` or `tokio 1`.
//cc @akru can you try this to ensure that it actually fixes your issue ^^

[jsonrpsee http client]: support tokio1 & tokio02.

---

Cargo.toml
proc-macro/Cargo.toml
proc-macro/src/call.rs
proc-macro/src/store.rs
src/extrinsic/signer.rs

Use async-trait

---

Cargo.toml
client/Cargo.toml
client/src/lib.rs
src/error.rs
src/lib.rs
src/rpc.rs
src/subscription.rs

The rationale is behind this bump is https://github.com/paritytech/jsonrpsee/pull/274 and that the client API has been changed to avoid less allocations.
Also we have released the `jsonrpsee root` crate again but it doesn't expose `tokio02` feature to won't work for this repo yet :(

update jsonrpsee to 0.2.0-alpha.6

---

src/lib.rs
src/rpc.rs

This makes the life of the downstream user easier.
With `Client`, we can only access the public methods exposed in it
but that does not cover all the RPC interfaces provided by the chain.
Therefore, the user of this library has to build another `RpcClient` for
the uncovered RPC interfaces, which can be unnecessary.

Expose the rpc client in Client

---

Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml
src/runtimes.rs

This patch is simply for easier editor operation when replacing the
substrate deps. No code changes.

Reorg the order of deps

---

Cargo.toml
client/Cargo.toml
client/src/lib.rs
src/lib.rs
src/rpc.rs
src/subscription.rs
src/tests/mod.rs

The motivation is to avoid pinning certain alpha versions and to avoid
breaking users builds without having to some `Cargo.lock` updating.
I had to add the `tokio1 compat` flag to `async-std` in order to because we don't use `async-std` anymore in `jsonrpsee`

deps: update jsonrpsee 0.2.0

---

Cargo.toml
client/Cargo.toml
proc-macro/Cargo.toml
src/error.rs
src/events.rs
src/metadata.rs

(Referencing substrate this way you only have to search and replace one string to upgrade)

Updated to later version of substrate so that it compiles.

---

codegen/src/types/tests.rs
codegen/src/types/type_def.rs

This fix is required for calls that embed other calls, such as `sudo` and `batch`. Without it, these calls fail if the explicit index provided in the metadata does not match the implicit index of the enum variant

Codegen: enum variant indices

---

src/events.rs
src/subscription.rs

When processing a block, the code immediately returned any encountered errors. Any events produced in the block after the error would be silently dropped. This pr changes the behavior: an error is now handled in the same way as events. That is, they are added to the `VecDeque` and are returned only when they get popped from there. This ensures that all events from the block are correctly processed

fix: keep processing a block's events after encountering a dispatch error

---

cli/Cargo.toml
cli/README.md
codegen/Cargo.toml
macro/Cargo.toml

In order to be able to use `subxt-cli` for downloading metadata. See https://github.com/paritytech/subxt/pull/319#discussion_r748193904

Release initial versions of `subxt-codegen` and `subxt-cli`

---

src/client.rs
src/extrinsic/extra.rs
src/extrinsic/mod.rs

We need to control the transaction longevity in our application. subxt does's have an API to do so.
We can use a custom SignedExtra implementation to fill the CheckMortality parameters. However, a custom SignedExtra has no way to be passed in extra infomation to construct the CheckMortality. This PR add an associated type to allow SignedExtra to carry some custom data to construct the signed extra.  Check [here](https://github.com/Phala-Network/phala-blockchain/blob/db56f7a6e6f490aa68d6ba2af6a498e597e8ea04/crates/phaxt/src/extra.rs#L66-L87) for more detail.

Additional parameters for SignedExtra

---

src/subscription.rs

Supersedes #283. It's modified based on [your comment there](https://github.com/paritytech/subxt/pull/283#issuecomment-961876200) and it's included in the unit test

fix: also processess initialize and finalize events in event subscription

---

Cargo.toml
src/error.rs
src/rpc.rs
src/subscription.rs

Includes https://github.com/paritytech/jsonrpsee/pull/578 which should fix errors containing quoted  strings.

Update to jsonrpsee 0.5.1

---

.github/issue_templates/nightly_run_failed.md
.github/workflows/nightly.yml

- Point to the failures in the issue generated by the nightly action
- Only run nightly test once

Fix a couple of CI niggles

---

cli/src/main.rs
codegen/src/ir.rs
codegen/src/types/tests.rs
src/client.rs
src/metadata.rs
src/rpc.rs
tests/integration/frame/timestamp.rs

Closes #316.
System properties are just an arbitrary JSON object defined in the chainspec, so this should be reflected in `subxt`. See https://github.com/paritytech/substrate/blob/b7409a2257c7c231b485ee827daa73d05d303047/client/chain-spec/src/lib.rs#L148
Additionally to satisfy CI:
- Makes timestamp test not flaky
- Fixes clippy errors and warnings

Make system properties an arbitrary JSON object, plus CI fixes

---

Cargo.toml
src/lib.rs

Micro PR with outcome of some code reading and tinkering.
Moves `sp-arithmetic` to `dev-dependencies` and switches to use `default-features = false`. Was hoping for a reduced number of dependent crates but it stays the same.﻿

Simpler dependencies

---

examples/submit_and_watch.rs
src/transaction.rs

And make `has_event` take `&self`; it does not need or want ownership.

Expand the `subscribe_and_watch` example

---

test-runtime/Cargo.toml
test-runtime/build.rs

Prior to this, one could update the substrate binary on their PATH, and the test-runtime would not rebuild in response to this, leading to a potentially out of date runtime being used (the fix was to tweak `test-runtime/build.rs` to force a rebuild).
This resolves the path to the substrate binary and tells cargo to keep an eye on that, too.
Tested by `touch`ing the substrate binary in use, which then caused a rebuild (and otherwise it would not rebuild).
Closes #358

Rebuild test-runtime if `substrate` binary is updated

---

src/lib.rs

It is returned by several public methods on `TransactionInProgress` and `TransactionInBlock`.

Export TransactionEvents

---

macro/Cargo.toml
src/extrinsic/extra.rs

`pre_dispatch` is a new method on the `SignedExtension` trait from substrate. We don't care about this internal implementation detail on the `subxt` side, but we require this trait to be implemented because we are using the `SignedPayload` and `UncheckedExtrinsic` types from `sp_runtime`.
The other option is of course to define our own local types and traits to remove this direct coupling, but that need some careful consideration.
In the meantime this makes things compile and continue working against the `substrate` master branch.
This also fixes an issue with duplicate substrate dependencies.

Implement `pre_dispatch` for SignedExtensions

---

.github/workflows/nightly.yml
Cargo.toml
examples/submit_and_watch.rs
src/error.rs
src/rpc.rs
src/subscription.rs
src/transaction.rs
tests/integration/client.rs

Update to using jsonrpsee 0.7
With the 0.7 update to `jsonrpsee` we now also implement `futures::Stream` on `TransactionProgress` to open up access to the various `StreamExt` combinator methods and such.

Update to jsonrpsee 0.7 and impl Stream on TransactionProgress

---

Cargo.toml
examples/fetch_remote.rs

The port number is required in the `url` for the remote node. 
Also `client-ws-transport` feature needs to be specified for `wss` to be handled properly.

fix remote example

---

src/rpc.rs
tests/integration/client.rs

I find this additional information useful to be available from a client tool perspective. And goes in line with the methods available in `polkadot.js`.

fetch system chain, name and version

---

Cargo.toml
src/client.rs
src/config.rs
src/events.rs
src/extrinsic/extra.rs
src/lib.rs
src/storage.rs
src/transaction.rs

We use types implementing the `Config` trait in Subxt, but only at compile-time; we never instantiate an instance of them. And yet, the Config trait has various bounds on it (`Debug`, `Clone`, `Copy`, `Send`, `Sync` etc).
This PR removes those bounds (well, mostly; `'static` is still there for now and should be able to go away eventually, but that should never complicate anything in real use).
The reason I think that these bounds existed in the first place is that Rust's inbuilt "derive" mechanism is quite primitive (eg deriving `Clone` will derive something like `impl <T: Clone> Clone for MyType<T>`; the `T` also needs to be `Clone`). As a result, we ended up with a bunch of additional bounds on the `Config` type so that it could be passed around as a generic type `T` and would still …

Remove bounds on Config trait that aren't strictly necessary

---

src/client.rs
src/extrinsic/mod.rs
src/rpc.rs

This came about because `stateVersion` went away in a recentish version of substrate/polkadot, which started breaking `subxt` which was quite strict in what it expected to be decoded.
Here we make the decoding more lenient, only expecting the props we need and keeping props that exist but aren't needed in a `HashMap` incase they are useful to others.

Make own version of RuntimeVersion to avoid mismatches

---

src/transaction.rs

Exposing `transaction::TransactionProgress` will allow customs implementation of extrinsic submission without being bound to signing in subxt.
```rust
async fn submit_then_watch<'client>(
client: &'client Client<DefaultConfig>,
ext_hash: H256,
signed_tx: Bytes,
) -> Result<TransactionProgress<'client, DefaultConfig>, parity_scale_codec::Error> {
let sub = client.rpc().watch_extrinsic(signed_tx).await.unwrap();
Ok(TransactionProgress::new(sub, client, ext_hash))
}
let events = submit_then_watch(&api, ext_hash, signed_tx)
.await
.unwrap()
.wait_for_finalized_success()
.await
.unwrap();
```

Expose transaction::TransactionProgress as `public`

---

codegen/src/api/storage.rs

Make the fields in a storage map key with more than one value public, too. 
Closes #403

make storage-n-map fields public too

---

cli/src/main.rs

Add custom derive command for cli
Example
```
subxt codegen --url https://pangolin-rpc.darwinia.network --derive Clone --derive Other
```

Custom derive for cli

---

codegen/src/api/constants.rs
codegen/src/api/mod.rs
tests/integration/frame/balances.rs

add constants api to codegen

---

codegen/src/api/calls.rs
codegen/src/api/events.rs
codegen/src/api/mod.rs
codegen/src/types/composite_def.rs
codegen/src/types/tests.rs

Fixes #410.
Unfortunately there are no tests (yet) for the `Call` struct codegen from variants so that aspect is not tested here.

Only convert struct names to camel case for Call variant structs

---

src/rpc.rs

While troubleshooting #399, I wanted to look at the raw bytes returned from the storage query before attempting to decode. Previously this was logged by `jsonrpsee`, but no longer.
This is useful since we can just ask users to enable `RUST_LOG=debug` for their client/test and we can then easily check the decoding of the raw bytes..

Log debug message for JSON-RPC response

---

subxt/src/subscription.rs
test-runtime/build.rs

Currently, the `next` method on the `EventSubscription` type only returns the event itself, not clarifying where it occurred. This PR introduces a new method, `next_context`, that additionally returns the corresponding block hash and the index of the event.
Btw, I think it would be great to have a block number, too, but I think that'd require upstream substrate changes (or additional queries on `subxt`'s side).
Feedback/criticism appreciated.
EDIT: Will wait for your feedback before I'll resolve the conflicts.

Get event context on EventSubscription

---

examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
test-runtime/Cargo.toml

In order to use the recently released `pallet-contracts-primitives` from https://github.com/paritytech/cargo-contract/pull/79, I need to update the common Substrate dependencies here to `5.0.0`.

Update substrate dependencies

---

subxt/src/events.rs
test-runtime/README.md
test-runtime/build.rs

Test code branches of `decode_and_consume_type` in isolation (issue #414).
While at it, fix some typos and add explicit error handling for missing substrate binary.

Add more tests for `events.rs/decode_and_consume_type`

---

CHANGELOG.md
RELEASING.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
subxt/src/lib.rs
test-runtime/Cargo.toml

Release preparation for v0.17.0

Release preparation for v0.17.0

---

subxt/Cargo.toml

A hopefully fairly temporary fix which leads to the "std" feature is enabled on `sp-runtime-interface` (it's the only default feature) in order to avoid an assertion check.
closes #437

Set "std" feature on sp-runtime to avoid a static assertion error

---

codegen/src/lib.rs
codegen/src/types/mod.rs

I require it for a macro to generate Rust API for `ink!` contracts for benchmarking. This prototype could one day be promoted to it's own crate, or even integrated here :grin:

Export `codegen::TypeGenerator`

---

subxt/src/client.rs

When manually managing an account's `nonce` via `set_nonce` and `increment_nonce`, the current account nonce is not fetched by default but has to be manually initialized. The tricky thing is knowing what the current valid nonce is.
This PR extracts a method which allows fetching the current value of an account's nonce via `Client`, so we can initialize it with `signer.set_nonce`.
Possibly there is a nice API we could add which would perform this one-time initialization, but better to start with allowing it to be done explicitly. In any case it is useful to be able to query the current account nonce.

Expose method to fetch nonce via `Client`

---

CHANGELOG.md
cli/Cargo.toml
codegen/Cargo.toml
codegen/src/types/tests.rs
codegen/src/types/type_path.rs
examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
subxt/src/events.rs
subxt/src/events/decoding.rs
subxt/src/lib.rs
subxt/tests/integration/codegen/polkadot.rs
test-runtime/Cargo.toml

It seems this will also need releasing all the substrate deps again with the matching requirements :see_no_evil:

Update scale-info and parity-scale-codec requirements

---

CHANGELOG.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
test-runtime/Cargo.toml

Release preparation for v0.18.0

Release preparation for v0.18.0

---

subxt/Cargo.toml
subxt/src/storage.rs
subxt/src/transaction.rs

We had already copied in the one struct we need from this anyway, since it changed between versions and we only needed to decode a subset of it, but because the `use sp_version` declarations were `pub`, they weren't spotted as unneeded.

Remove unused sp_version dependency

---

CHANGELOG.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
test-runtime/Cargo.toml

- This removes a dependency on an old version of parity-scale-codec by removing a now unused `sp-runtime` dependency.

Release prep for 0.18.1

---

subxt/src/events/event_subscription.rs
subxt/src/events/filter_events.rs
subxt/src/rpc.rs
subxt/tests/integration/events.rs

Without this, they cannot be used in `tokio::spawn`-like contexts, which require things held across await points to impl `Send` (because they might be moved across threads between such points).
Closes #469

Make EventSubscription and FilterEvents Send-able

---

codegen/src/api/mod.rs
examples/examples/rpc_call.rs
subxt/Cargo.toml
subxt/src/config.rs
subxt/src/events/event_subscription.rs
subxt/src/events/mod.rs
subxt/src/rpc.rs
subxt/tests/integration/codegen/polkadot.rs
subxt/tests/integration/events.rs

If you subscribe to receive finalized block headers, blocks may be skipped over whenever a bunch of them are finalized at the same time. This PR makes sure to return events from all of the skipped-over blocks too.
Closes #468

Return events from blocks skipped over during Finalization, too

---

RELEASING.md
scripts/generate_changelog.sh

This script is intended to automate part of the release process.
As stated in the [release](https://github.com/paritytech/subxt/blob/master/RELEASING.md), the changelog should be created from closed PRs.
In this approach, the script inspects the merged PRs into the main branch `origin/master`, that is similar to what the substrate repository does.
*  ``` shellcheck ./scripts/generate_changelog.sh ```
* Output without commits
```
./scripts/generate_changelog.sh
[+] Latest release tag: v0.18.0
[+] Changelog
```
* Output with commits
```
./scripts/generate_changelog.sh
[+] Latest release tag: v0.17.0
[+] Changelog
- Release preparation for v0.18.0 ([#464](https://github.com/paritytech/subxt/pull/464))
- Reference key storage api ([#447](https://github.com/paritytech/subxt/pull/447))
- Update …
```

Generate release changelog based on commits

---

CHANGELOG.md
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
subxt/Cargo.toml
test-runtime/Cargo.toml

#471 in-particular has come up a few times now, so the main impetus for this release is getting that out there, so that event subscriptions are able to be carried out in things like tokio tasks without hitting `Send` related issues.
Changes:
- Return events from blocks skipped over during Finalization, too ([#473](git@github.com:paritytech/subxt/pull/473))
- Use RPC call to get account nonce ([#476](git@github.com:paritytech/subxt/pull/476))
- Add script to generate release changelog based on commits ([#465](git@github.com:paritytech/subxt/pull/465))
- README updates ([#472](git@github.com:paritytech/subxt/pull/472))
- Make EventSubscription and FilterEvents Send-able ([#471](git@github.com:paritytech/subxt/pull/471))

Release prep for 0.19.0

---

subxt/src/rpc.rs

Add support for a new RPC added here: https://github.com/paritytech/substrate/pull/10939
A WIP tool that already uses this can be found here: https://github.com/athei/povstats

Add `dev_getBlockStats` RPC

---

examples/Cargo.toml
examples/examples/balance_transfer.rs
examples/examples/balance_transfer_with_params.rs
examples/examples/custom_config.rs
examples/examples/custom_type_derives.rs
examples/examples/fetch_all_accounts.rs
examples/examples/fetch_staking_details.rs
examples/examples/rpc_call.rs
examples/examples/submit_and_watch.rs
examples/examples/subscribe_all_events.rs
examples/examples/subscribe_one_event.rs
examples/examples/subscribe_some_events.rs
subxt/Cargo.toml
subxt/src/events/filter_events.rs
subxt/tests/integration/client.rs
subxt/tests/integration/events.rs
subxt/tests/integration/frame/balances.rs
subxt/tests/integration/frame/contracts.rs
subxt/tests/integration/frame/staking.rs
subxt/tests/integration/frame/sudo.rs
subxt/tests/integration/frame/system.rs
subxt/tests/integration/frame/timestamp.rs
subxt/tests/integration/storage.rs
test-runtime/Cargo.toml
test-runtime/build.rs

Remove the `async-std` dependency and utilize `tokio` instead.
This is motivated by the fact that `jsonrpsee` utilizes under the hood `tokio`.
Closes #485.

Use tokio instead of async-std

---

subxt/tests/integration/utils/node_proc.rs
test-runtime/build.rs

The testing infrastructure requires that a `substrate` binary is present for individual testing.
However, having a different `polkadot` binary running resulted in failing tests.
The function `next_open_port()` in `subxt` crate produced 3 port numbers by inspecting
a range of ports. 
To validate that a given port is opened the `TcpListener::bind(("0.0.0.0", 0))` bind call is executed.
However, the address "0.0.0.0" is not representative of the localhost, but of a non-routable unknown address.
This observation is validated using the `polkadot` binary which starts by default on `127.0.0.1:9944`. Any `TcpListener::bind(("0.0.0.0", 0))` will result in success even with the binary started.
While at it, remove the scanning logic and rely entirely on the Kernel to provide 3 available ports.
The …

Rely on the kernel for port allocation

---

subxt/src/lib.rs

Without this we cannot match on error variants produced by calls.

export ModuleError for downstream matching

---

codegen/src/api/calls.rs
codegen/src/api/constants.rs
codegen/src/api/mod.rs
codegen/src/api/storage.rs
codegen/src/types/composite_def.rs
codegen/src/types/type_def.rs
subxt/tests/integration/codegen/polkadot.rs

This PR propagates the documentation from the metadata blob to the generated API.
The documentation is propagated to either TransactionApi or StorageApi if the inspected type is a call or storage, instead of being placed directly on the generated object.
This is done mainly to document the paths by which the user interacts with the API, as opposed to documenting the inner details of the API. For other types, the metadata documentation is set in place for the generated object.
```rust
impl<'a, T: ::subxt::Config> StorageApi<'a, T> {
...
#[doc = " The full account information for a particular account ID."]
pub async fn account(
```
```rust
pub struct TransactionApi<'a, T: ::subxt::Config, X> {
...
#[doc = "Anonymously schedule a task."]
pub fn schedule(
```
```rust
pub struct …
```

Propagate documentation to runtime API

---

subxt/src/extrinsic/mod.rs

In https://github.com/paritytech/cargo-contract/pull/523 I have used `PolkadotExtrinsicParams` which is just an alias for `BaseExtrinsicParams<T, PlainTip>`. 
However my target chain is not a polkadot node so this is a misleading name, I would rather use ``BaseExtrinsicParams<T, PlainTip>` directly.
Note the alternative to this would be to rename the aliases to something like `BaseExtrinisicParamsWithPlainTip` and `BaseExtrinsicsParamsWithAssetTip`.

Export `BaseExtrinsicParams`

---

test-runtime/build.rs

The PR ensures that the `test-runtime`' can fetch the metadata from the spawned substrate binary.
Closes #517.

test-runtime: Add exponential backoff

---

integration-tests/src/metadata/validation.rs

The issue was related to holding the internal subxt's client metadata
`RwLock` between multiple await points.
This PR ensures the metadata is cloned and the lock guard dropped
immediately.

Fix clippy for holding locks between multiple awaits

---

cli/Cargo.toml
cli/src/main.rs
codegen/src/lib.rs
integration-tests/Cargo.toml
integration-tests/src/lib.rs
macro/src/lib.rs
subxt/Cargo.toml
subxt/src/lib.rs

I haven't added it for the `metadata` crate since it wants to remove some benchmark target dev dependencies

Deny unused crate dependencies

---

.github/dependabot.yml
CODEOWNERS

This PR adds GitHub Actions monitoring to the Dependabot
As well CODEOWNERS file added with @paritytech/ci team added as `./.github/` folder codeowner. This is needed for us to receive notifications and track changes mainly about GHA changes. Related issues https://github.com/paritytech/ci_cd/issues/407 and https://github.com/paritytech/ci_cd/issues/464
Feel free to propose/add additional entries to CODEOWNERS

Add GitHub Actions to Dependabot and CODEOWNERS

---

codegen/src/ir.rs
testing/test-runtime/build.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.stderr
testing/ui-tests/src/lib.rs

This PR validates that substitute types have a global absolute path to ensure 
the type is accessible at every level of the module hierarchy.
To ensure that paths are absolute global paths they must be:
- prefixed by `::`
- or prefixed by `crate`
For validation purposes, a new `ui` test is added to capture compile failures.
Closes #539.

Validate absolute path for `substitute_type`

---

subxt/src/client.rs

Expose the SCALE encoded call data of an extrinsic

---

metadata/src/lib.rs
testing/integration-tests/src/metadata/validation.rs

The goal of metadata validation is checking for compatibility between metadatas, not equality, so no need to hash the value of constants; that'll just lead to calls to obtain them failing that should succeed.
Also we don't need to hash the name of the constant when we are looking up the constant by name anyway.

Don't hash constant values; only their types

---

codegen/src/types/type_def_params.rs
metadata/src/lib.rs
subxt/src/events/event_subscription.rs
testing/integration-tests/src/metadata/validation.rs

The #591 presented a metadata validation issue detected on the [Snowbridge](https://github.com/Snowfork/snowbridge) parachain.
The metadata validation would reject extrinsics due to the following difference in metadata:
| Source|  Metadata |
| --- | --- |
| snowbridge | "typeName": "/*«*/ u32 /*»*/" |
| polkadot | "typeName": "u32"|
This PR removes the hashing of the `typeName` as the unique deterministic representation of the field is deduced from its `type` and `name`. 
Utilizing the metadata provided in the issue:
```bash
subxt-cli -- codegen --file ours.metadata.scale > ours.rs
subxt-cli -- codegen --file theirs.metadata.scale > theirs.rs
diff ours.rs theirs.rs
#ok - identical hashes for validation
```

metadata: Exclude `field::type_name` from metadata validation

---

subxt/Cargo.toml
subxt/src/events/events_type.rs
subxt/src/events/filter_events.rs
testing/integration-tests/src/frame/balances.rs

Skip over event bytes using the `IgnoreVisitor` from `scale_decode`, and only decode fields into `Value`s if we ask for them explicitly.
Also avoid cloning event bytes around the place by reusing the same Vec (`Arc<[u8]>`) everywhere and avoiding any string cloning (again, pushing the work until the user asks for pallet/variant name), and tidy the API around working with events a little.
This builds off the big API change of #593.

Use scale-decode to help optimise event decoding

---

subxt/src/tx/tx_progress.rs

Redo #606 now that the big PR has merged, since it seems sensible!

Expose the extrinsic hash from TxProgress

---

CHANGELOG.md
examples/examples/custom_type_derives.rs
subxt/src/events/events_type.rs
subxt/src/metadata/metadata_type.rs
subxt/src/rpc.rs
testing/integration-tests/src/events/mod.rs

Just adding a test and tweaking the 0.23 release notes to note a function behaviour change that Andrew ran into.

Tweak 0.23 notes and add another test for events

---

codegen/src/api/mod.rs

Since we have a type override for H256 already, also add one for H160 and H512
Closes #619

use 'sp_core::Hxxx' for all hash types

---

subxt/src/tx/mod.rs
subxt/src/tx/tx_client.rs
testing/integration-tests/src/client/mod.rs

- add `create_unsigned` call to build unsigned extrinsics.
- rename `SignedSubmittableExtrinsic` to `SubmittableExtrinsic` (since you can now get one from an unsigned tx too).
- expose `encoded()` from this for OfflineClients too.
Todo:

Allow creating/submitting unsigned transactions, too.

---

subxt/src/constants/constants_client.rs
subxt/src/metadata/metadata_type.rs
subxt/src/storage/storage_client.rs
subxt/src/tx/tx_client.rs

This PR specializes the metadata errors to contain information
about the incompatible components, for static validation purposes.
Closes #584.

Specialize incompatible metadata errors

---

.github/workflows/nightly.yml
.github/workflows/rust.yml

In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies

pin gha versions

---

subxt/src/rpc.rs

Needed for https://github.com/paritytech/ink/issues/1234.
Shamelessly copied from `sp-rc`, which I guess you wanted to avoid as a dep.

Add conversion and default functions for `NumberOrHex`

---

subxt/src/tx/tx_client.rs
subxt/src/tx/tx_payload.rs

Most custom implementations will not do static validation, and for these, there's no need to require that a pallet and call name can be handed back. This tweak to the trait signature makes that clear.
I also exposed a way to create a `SubmittableExtrinsic` without going through the previous steps, in case somebody has bytes for a pre-signed extrinsic that they'd like to submit.
In response to #637 (though I think their issue is unrelated, it'll help with this sort of thing)

Simplify the TxPayload trait a little

---

subxt/src/tx/tx_client.rs
testing/integration-tests/src/client/mod.rs
testing/integration-tests/src/frame/contracts.rs
testing/integration-tests/src/frame/sudo.rs

Just a small PR to do what the title says :)

Remove unnecessary async and fix latest substrate changes

---

CHANGELOG.md
subxt/src/events/events_type.rs
subxt/src/metadata/metadata_type.rs

Fields in `EventMetadata` now also store name of a type specified in the pallet's source code.
Required for [#673](https://github.com/paritytech/cargo-contract/issues/673) in `cargo-contract`

Store type name of a field in event metadata

---

subxt/Cargo.toml
subxt/src/events/events_type.rs

These both compile to WASM, and so push us a little closer to getting the core of subxt also compiling to WASM

Bump scale-value and scale-decode

---

subxt/src/metadata/metadata_type.rs
subxt/src/metadata/mod.rs

Follow up to #654, the type should be exported.

Export EventFieldMetadata

---

subxt/src/tx/tx_payload.rs

This might be required e.g. for `state_call` RPCs where the encoded `call_data` is without pallet and call index prefixes.

Add accessor for `StaticTxPayload::call_data`

---

examples/examples/subscribe_runtime_updates.rs
subxt/src/client/mod.rs
subxt/src/client/online_client.rs

Closes https://github.com/paritytech/subxt/issues/652

feat: add low-level `runtime upgrade API`

---

cli/src/main.rs
codegen/src/api/calls.rs
codegen/src/api/constants.rs
codegen/src/api/events.rs
codegen/src/api/mod.rs
codegen/src/api/storage.rs
codegen/src/lib.rs
codegen/src/types/composite_def.rs
codegen/src/types/derives.rs
codegen/src/types/mod.rs
codegen/src/types/tests.rs
codegen/src/types/type_def.rs
codegen/src/types/type_path.rs
macro/src/lib.rs
testing/integration-tests/src/codegen/codegen_documentation.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.stderr

Closes https://github.com/paritytech/subxt/issues/655.
We need this in ink! for https://github.com/paritytech/ink/issues/1234.
I'm not particularly fond of the testing story for this feature, but I would also not duplicate all the existing tests. Hmm.

Allow specifying the `subxt` crate path for generated code

---

testing/integration-tests/src/frame/contracts.rs
testing/integration-tests/src/frame/sudo.rs

Fix the subxt testing against the latest substrate binary regarding the following errors
```rust
--> testing/integration-tests/src/frame/sudo.rs:62:38
|
62 |         .sudo_unchecked_weight(call, Weight { ref_time: 0 });
|                                      ^^^^^^ missing `proof_size`
```

fix: Add `proof_size` field for the `Weight`

---

testing/integration-tests/src/frame/contracts.rs

Prior to https://github.com/paritytech/substrate/pull/12383, setting `proof_size` to `0` worked for all extrinsics. Following that a proper value needed to be supplied. However `u64::MAX` was too high as it breached the limit for normal class transactions weight (I think about `0.75 * MAX_BLOCK_WEIGHT`).
Interestingly `0` still worked for `instantiate_with_code` and `call`, but the fix was to set it to `u64::MAX / 2`.

Fix contracts integration test

---

cli/Cargo.toml
cli/src/commands/codegen.rs
cli/src/commands/compatibility.rs
cli/src/commands/metadata.rs

Upgrade clap to v4

---

examples/examples/custom_rpc_client.rs
subxt/src/client/online_client.rs
subxt/src/events/mod.rs
subxt/src/rpc/rpc.rs
subxt/src/rpc/rpc_client.rs

We depend on the jsonrpc-core client so we can make typed rpc requests
eg: https://github.com/ComposableFi/hyperspace/blob/311bc18ac6d4b24ed4586ba98552e9e145b0b068/parachain/src/provider.rs#L335-L342

expose jsonrpc-core client

---

examples/examples/dynamic_queries.rs
subxt/src/constants/constant_address.rs
subxt/src/dynamic.rs
subxt/src/storage/storage_address.rs
testing/integration-tests/src/frame/balances.rs

When you make a dynamic storage or constant query at the moment, you get back a `Value`. In some cases, you might just want the raw SCALE bytes back to do as you wish with (eg here: https://github.com/paritytech/staking-miner-v2/pull/387/files#diff-6e448cdd99756118d32afe57b3d7d260cb1626cdbdbace46a91f1f9d20aabd4eR118.).
This PR makes dynamic things decode into this intermediate `DecodedValueThunk` type, from which you can either finish decoding into a value with `.to_value()` or access the bytes with `.to_encoded()` to do as you wish with instead.

Make it possible to get raw bytes back from dynamic constant/storage queries

---

subxt/src/config.rs

This fixes the `future is not Send as this value is used across an await
` error  when calling `TxInBlock::wait_for_success`
Current Error I get when I call that function

Make Config::Extrinsic `Send`

---

subxt/src/tx/tx_client.rs

This is useful for something like this:
```rust
let balances_transfer_tx = ...;
let signed_balances_transfer_tx = api
.tx()
.create_signed(&balances_transfer_tx, signer, Default::default())
.await?;
let extrinsic_hash = Hashing::hash(signed_balances_transfer_tx.encoded());
// We need `extrinsic_hash` because we want to log it, before we try to submit and watch the extrinsic.
// We can't use `signed_balances_transfer_tx.submit_and_watch()` as we want to avoid doing the work twice.
debug!(
message = "Balance transfer extrinsic signed",
?address,
?extrinsic_hash
);
// Manually do the `watch_extrinsic`.
let sub = api
.rpc()
.watch_extrinsic(Encoded(signed_balances_transfer_tx.into_encoded())) // <---- this is where we need the new API
.await?
let mut progress = …
```

Allow taking out raw bytes from a SubmittableExtrinsic

---

codegen/src/types/type_def.rs
subxt/src/dynamic.rs

to_encoded => into_encoded for consistency from #683

into_encoded() for consistency

---

cli/src/commands/codegen.rs
cli/src/commands/compatibility.rs
cli/src/commands/metadata.rs
codegen/Cargo.toml
codegen/src/api/mod.rs
codegen/src/lib.rs
codegen/src/utils/fetch_metadata.rs
codegen/src/utils/mod.rs
examples/examples/custom_metadata_url.rs
macro/src/lib.rs
testing/ui-tests/src/incorrect/need_url_or_path.rs
testing/ui-tests/src/incorrect/need_url_or_path.stderr
testing/ui-tests/src/incorrect/url_and_path_provided.rs
testing/ui-tests/src/incorrect/url_and_path_provided.stderr

And reuse this fetch functionality in the CLI crate to avoid duplication.
Closes #640

Add runtime_metadata_url to pull metadata directly from a node

---

codegen/src/utils/fetch_metadata.rs

This PR increases the request timeout required to fetch the
metadata from a running node.
The metadata is fetched at build time using the code-gen logic,
but the operation can timeout if the target node (obtained from the load
balancer) or network path is overwhelmed.
This fixes the issue detected by our CI by increasing the timeout
of a request from 1minute to 3minutes. 
Closes #695.

codegen: Increase request timeout from 1min to 3min

---

subxt/src/client/online_client.rs
subxt/src/error.rs
subxt/src/rpc/jsonrpsee_impl.rs
subxt/src/rpc/rpc_client_t.rs
subxt/src/tx/tx_progress.rs

This PR extends the `RpcError` error to support two variants:
- custom error originated from the RPC client (this is boxed to allow users to cast the error, without needlessly having the error generic)
- custom string originated from subxt (ie, parsing parameters). 
Closes #692.

error: `RpcError` with custom client error

---

subxt/src/tx/signer.rs
subxt/src/tx/tx_client.rs

We can create transactions and provide separate nonces now, so there is no need to expose this nonce functionality in the Signer trait, which shouldn't need to care.

No need to entangle Signer and nonce now

---

testing/ui-tests/Cargo.toml
testing/ui-tests/src/utils/dispatch_error.rs

Okay so it turns out `2.3` did have some breaking changes after all, we didn't see it in `substrate` or `ink` because none of those used the `FieldsBuilder::<NamedFields>::default()` method.
This PR uses the idiomatic convenience methods `Fields::named()` and `unnamed()` instead.

Upgrade to scale-info 2.3 and fix errors

---

.github/workflows/rust.yml

This PR installs chrome and firefox explicitly to ensure that wasm-pack finds the chrome and firefox drivers.

fix(ci): wasm tests

---

codegen/src/api/mod.rs
codegen/src/ir.rs
testing/ui-tests/src/correct/rust-items-preserved.rs
testing/ui-tests/src/lib.rs

Retain Rust code items from `mod` decorated with `subxt` attribute

---

subxt/src/client/online_client.rs
subxt/src/events/events_client.rs
subxt/src/events/events_type.rs
subxt/src/rpc/rpc.rs

The events are using the client metadata for dynamic decoding.
However, the users are allowed to inspect the events at an arbitrary block.
If the arbitrary block is a block where a runtime upgrade happened that
changed the metadata content, the dynamic decoding of the events
would fail.
To mitigate this scenario, expose the ability to query the metadata at
an arbitrary block, and fetch the metadata of a block when fetching the
block events.
This ensures that dynamic decoding of events will succeed if an arbitrary
block hash is provided.
The client is encouraged to keep the metadata in sync via subscriptions
to the runtime upgrade.
Closes: https://github.com/paritytech/subxt/issues/725

events: Fetch metadata at arbitrary blocks

---

subxt/src/lib.rs

Removed in Rust 1.66:
```
warning: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
--> subxt/src/lib.rs:114:5
|
114 |     const_err,
|     ^^^^^^^^^
|
= note: `#[warn(renamed_and_removed_lints)]` on by default
```

Remove a soon-to-be-removed `const_err` lint

---

examples/examples/custom_rpc_client.rs
subxt/src/rpc/jsonrpsee_impl.rs
subxt/src/rpc/mod.rs
subxt/src/rpc/rpc_client.rs
subxt/src/rpc/rpc_client_t.rs

Extent the `RpcClientT` to obtain the ID associated with subscriptions.
To ensure that this extension is not impacting users that do not want to
implement/return it, the subscription ID is optional.
The subscription ID needs to be exposed for implementing https://github.com/paritytech/subxt/issues/732.

rpc: Expose the `subscription ID` for `RpcClientT`

---

subxt/src/events/events_type.rs

Fix decoding events via `.as_root_event()` and add test

---

.github/workflows/nightly.yml
.github/workflows/rust.yml

The nightly CI has detected a failure in a subxt UI test (https://github.com/paritytech/subxt/issues/779).
In order to gain better knowledge into what version of substrate we are using, this PR outputs the `substrate --version`.

ci: Print substrate version

---

testing/ui-tests/Cargo.toml
testing/ui-tests/src/correct/rust-items-preserved.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.rs
testing/ui-tests/src/incorrect/url_and_path_provided.rs
testing/ui-tests/src/incorrect/url_and_path_provided.stderr

Use the latest version of trybuild `1.0.76` and adjust the path to the scale metadata blob for UI testing.

Update `trybuild` to the latest version

---

codegen/src/api/mod.rs
testing/integration-tests/src/codegen/codegen_documentation.rs

Closes #775 and allows arbitrary attributes to be kept as needed on codegen module.

Codegen: Preserve attrs and add #[allow(clippy::all)]

---

subxt/src/utils/account_id.rs

With some exposed functions `AccountId32` can replace `AccountId32` from substrate

Implement deserialize

---

cli/Cargo.toml
cli/build.rs
cli/src/commands/mod.rs
cli/src/commands/version.rs
cli/src/main.rs

Builds off  @DaviRain-Su's work in #776 and provides version info in the subxt CLI command, making the git hash be a compile-time included string.
Closes #739

Expose version info in CLI tool with build-time obtained git hash

---

subxt/src/client/mod.rs

This will allow for use of `apply_update` on the `OnlineClient` which is already exposed as public.
Closes #789

Expose `Update`

---

subxt/src/blocks/block_types.rs
subxt/src/client/offline_client.rs
subxt/src/client/online_client.rs
subxt/src/lib.rs
subxt/src/rpc/rpc.rs
subxt/src/runtime_api/mod.rs
subxt/src/runtime_api/runtime_client.rs
subxt/src/runtime_api/runtime_types.rs
testing/integration-tests/src/blocks/mod.rs
testing/integration-tests/src/client/mod.rs

This PR adds the ability to call into the runtime API of the subxt.
At this moment, the subxt utilises the `state_call` method.
This work lays the ground for transitioning to the `chainHead` and `archive` methods of the RPC SpecV2.
The API is exposed both at the root level via, as well at the blocks level (block-centric approach).
Part of #732 .

Add Runtime API to execute runtime calls

---

subxt/src/tx/tx_client.rs

This is a bug introduced in [#760](https://github.com/paritytech/subxt/pull/760/files#diff-2fb361b08d8543a8a513a3f16b7d44ed1d1105716427e00006c44e763cef8290R172).

Fix bad signature when the extrinsic size is over 256 bytes

---

subxt/src/client/mod.rs
subxt/src/client/online_client.rs

This allows one to instantiate clients capable of decoding older (as long as still V14) blocks and such, with suitable warnings that such clients may not be able to interact with the head of the chain and such.
Hopefully this closes #793

Add ability to set custom metadata etc on OnlineClient

---

cli/src/commands/codegen.rs
codegen/src/api/mod.rs
codegen/src/ir.rs
codegen/src/lib.rs
codegen/src/types/mod.rs
codegen/src/types/substitutes.rs
codegen/src/types/tests.rs
codegen/src/types/type_def.rs
examples/examples/multisig.rs
macro/src/lib.rs
testing/integration-tests/src/codegen/codegen_documentation.rs
testing/test-runtime/build.rs
testing/ui-tests/src/correct/generic-params.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.rs
testing/ui-tests/src/incorrect/substitute_path_not_absolute.stderr

Closes #666 
For now, this moves type substitution annotations from the use statements outside, to the `subxt` macro + separates some substitution logic. Opening as a draft for now to get feedback; next thing to work on is to implement the generic wrangling/reordering mentioned in #666.

Allow for remapping type parameters in type substitutions

---

testing/integration-tests/src/client/mod.rs

Test that subxt can submit properly extrinsics that are larger than 256 bytes.
This PR creates an extrinsic of 2MiB and submits it to a local node.
Specifically, there was a fix in #796 that ensures the signatures are created correctly for larger extrinsic payloads.
Without the fix from #796 results in `Transaction has a bad signature`.

tests: Ensure correct signing of extrinsics larger than 256 bytes

---

subxt/src/events/events_type.rs

In order to optimise the code present in this [PR](https://github.com/paritytech/cargo-contract/pull/965), used for this [issue](https://github.com/paritytech/cargo-contract/issues/777) fixing the wrong return of contract account id with `cargo contract instantiate`
At the moment, only the method was added, yet more integration tests should be. 
As @ascjones suggests, finding 'a pallet where we know that two of the same type of event will be raised by the same extrinsic' should be more relevant than just adding the same integration tests where `find_first` is used,
What do you think would be the best @jsdw ?

Add `find_last` for events_types

---

CHANGELOG.md
Cargo.lock
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
subxt/src/tx/tx_payload.rs
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml
testing/ui-tests/Cargo.toml

A small release mainly just to bump Substrate dependencies to latest
Closes #819 
Closes #806

Release v0.27.0

---

subxt/src/blocks/block_types.rs

Still to fix the [issue](https://github.com/paritytech/cargo-contract/issues/777) and complete this [PR](https://github.com/paritytech/subxt/pull/821), `find_last` was added for block types events. 
This time, it was tested for this [fix](https://github.com/paritytech/cargo-contract/pull/965)

Add `find_last` for block types 

---

CHANGELOG.md
Cargo.lock
cli/Cargo.toml
codegen/Cargo.toml
examples/Cargo.toml
macro/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml
testing/ui-tests/Cargo.toml

Release 0.27.1 for the change 
- Add `find_last` for block types ([#825](https://github.com/paritytech/subxt/pull/825))
For this (PR)[https://github.com/paritytech/cargo-contract/pull/965]

Release 0.27.1

---

examples/Cargo.toml
metadata/Cargo.toml
subxt/Cargo.toml
testing/integration-tests/Cargo.toml
testing/test-runtime/Cargo.toml

Bumping all `sp-*` dependencies to the newest versions. Helps with linking issue in `wasmtime` (https://github.com/bytecodealliance/wasmtime/issues/5768)

Bump Substrate dependencies

---

Cargo.lock
cli/src/commands/codegen.rs
codegen/src/api/calls.rs
codegen/src/api/constants.rs
codegen/src/api/events.rs
codegen/src/api/mod.rs
codegen/src/api/storage.rs
codegen/src/lib.rs
codegen/src/types/mod.rs
codegen/src/types/tests.rs
codegen/src/types/type_def.rs
macro/src/lib.rs
testing/integration-tests/src/codegen/codegen_documentation.rs

This PR exposes the `--no-docs` flag by the CLI.
When the flag is active the generated subxt API will not include the documentation from the metadata.
While at it, have also modified the `codegen` tests to check that no documentation present in the metadata-v14 is extracted on the generated API.
Closes: https://github.com/paritytech/subxt/issues/826.

codegen: Opt out of documentation

---

subxt/src/lib.rs

When the `substrate-compat` is enabled let's re-export `sp-core` and `sp-runtime` again for compatibility reasons.
Further, it easy to pick the wrong version of `sp-core` and `sp-runtime` so let's make the usage a bit smoother.
Close https://github.com/paritytech/subxt/issues/844

fix: re-export `sp-core` and `sp-runtime`

---

examples/examples/concurrent_storage_requests.rs
examples/examples/dynamic_queries.rs
examples/examples/fetch_all_accounts.rs
examples/examples/fetch_staking_details.rs
examples/examples/storage_iterating.rs
subxt/src/blocks/block_types.rs
subxt/src/blocks/blocks_client.rs
subxt/src/events/events_client.rs
subxt/src/storage/storage_client.rs
subxt/src/storage/storage_type.rs
subxt/src/tx/tx_progress.rs
testing/integration-tests/src/client/mod.rs
testing/integration-tests/src/frame/balances.rs
testing/integration-tests/src/frame/contracts.rs
testing/integration-tests/src/frame/staking.rs
testing/integration-tests/src/frame/system.rs
testing/integration-tests/src/frame/timestamp.rs
testing/integration-tests/src/storage/mod.rs

resolves #899 by providing a simplified API for `.at(Option<Hash>)` by specialization into `.at_latest()` and `.at(Hash)`  in various places:
- storage_client: the at() version does not require async + Result anymore
- blocks_client: both versions still require async + Result
- events_client: both versions still require async + Result

added at_latest
